define('template/mobile/tpl', function(require, exports, module) {
    /* beautify ignore:start */
    /* eslint-disable */
    var tpl = {
        layout: [
            '<div>',
                '<div class="M_head">',
                    '<slot name="user"></slot>',
                    '<div class="lasted">',
                        '<div class="l_tl">本月已连续签到</div>',
                        '<div class="num_wrap" data-role="sign-days"></div>',
                    '</div>',
                    '<div class="steps">',
                        '<div class="bar" data-role="cur-bar">',
                            '<span></span>',
                        '</div>',
                        '<div class="arrow arrow_up" data-role="btn-arrow"></div>',
                        '<div class="date" data-role="cur-calendar">',
                            '<div v-on:click="onCalShow()" class="month"></div>',
                            '<div class="days clearfix" data-role="cur-days-bar">',
                                '<div class="clearfix" style="width: 1500px;" data-role="cur-days">',
                                '</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                    '<div id="pl-account" class="M_account">',
                        '<div class="F_cnt">',
                            '<div class="balance">我的乐米：<i data-role="text-points"></i></div>',
                        '</div>',
                    '</div>',
                '</div>',
                '<slot name="task"></slot>',
                '<slot name="advertisement"></slot>',
                '<slot name="hero"></slot>',
                '<slot name="sign"></slot>',
                '<slot name="signSuccess"></slot>',
                '<slot name="signCalendar"></slot>',
            '</div>'
        ].join(''),
        signBg:[
            '<div class="L_bg" v-bind:style="{backgroundImage: \'url(\' + backgroundImg + \')\'}"></div>'
        ].join(),
        sign:[
            '<div>',
                '<app-signBg></app-signBg>',
                '<div class="L_ac" v-on:click="reqSignApi()">',
                    '<a href="javascript:;" class="ac_cnt">',
                        '<i class="icon_active"></i> 点击签到',
                    '</a>',
                '</div>',
            '</div>'
        ].join(''),
        signSuccess:[
            '<div>',
                '<app-signBg></app-signBg>',
                // 签到成功
                '<div class="L_sucess">',
                    '<div class="suc_box">',
                        '<div class="gift">',
                            '<img src="https://i1.letvimg.com/lc04_iscms/201704/07/14/25/8963b631974d427fb90ee6103d6a45d3.jpg">',
                        '</div>',
                        '<div class="qd">',
                            '<div class="qd_tl">签到成功</div>',
                            '<div class="benefit">获得<span>{{credit}}</span>乐米</div>',
                            '<div class="pro">本月连续签到：<span><i>{{lasted}}</i>天</span><span>{{extraContent}}</span></div>',
                        '</div>',
                        '<div class="yunshi">',
                            '<div class="item">',
                                '<span>今日运势:</span><span>{{fortune}}</span><a v-if="isleme" v-bind:href="href">{{btnContent}}</a>',
                                '<div class="source">来源：科技紫微星座网</div>',
                            '</div>',
                            '<div class="item">',
                                '<span>{{city}}</span><i v-bind:class="weatherIcon" class="icon_w"></i><span>{{temp}}</span><span>{{date}}</span>',
                                '<div class="source">来源：天气通</div>',
                            '</div>',
                        '</div>',
                    '</div>',
                    '<template v-if="!isEmpty">',
                    '<div data-role="packageDetail" class="hbao_wrap">',
                        '<a class="icon_hbao" v-bind:href="detailUrl"></a>',
                        '<span>领红包</span>',
                    '</div>',
                    '</template>',
                    '<template v-else>',
                    '<div data-role="packageEmpty" class="hbao_wrap hide">',
                        '<i class="icon_hbao icon_hbao_fail"></i>',
                        '<span>领完啦</span>',
                    '</div>',
                    '</template>',
                    '<a v-on:click="onCloseLayer()" href="javascript:;" class="C_f_cls"></a>',
                '</div>',
            '</div>'
        ].join(''),
        signCalendar: [
            // 签到日历浮层
            '<div>',
                '<app-signBg></app-signBg>',
                '<div class="L_cal" id="pl-sign-cal">',
                    '<div class="cal_box">',
                        '<div class="outline">',
                            '<div>您累计签到：<span data-role="text-total"></span> 天</div>',
                            '<div>本月连续签到：<span data-role="text-lasted"></span> 天</div>',
                            '<div>您是今天第 <span data-role="text-rank"></span> 位签到的乐迷！</div>',
                        '</div>',
                        '<div class="tab">',
                            '<div class="year">',
                                '<a href="javascript:;" class="pre" v-on:click="onPrevBtn()"></a><span data-role="text-date">{{curYear}}年{{curMonth}}月</span>',
                                '<a v-if="!nextHide" href="javascript:;" class="nxt" v-on:click="onNextBtn()"></a>',
                            '</div>',
                            '<ol class="week">',
                                '<li>Sun</li>',
                                '<li>Mon</li>',
                                '<li>Tue</li>',
                                '<li>Wed</li>',
                                '<li>Thu</li>',
                                '<li>Fri</li>',
                                '<li>Sat</li>',
                            '</ol>',
                            '<div class="day_wrap">',
                                '<table class="day" data-role="table-calendar">',
                                    '<tr v-for="(item,index) in calArray">',
                                        '<td v-for="(itemVal,indexVal) in item" v-bind:data-dateid="itemVal.dateid"><span>{{itemVal.date}}</span></td>',
                                    '</tr>',
                                '</table>',
                            '</div>',
                            // '<a class="red" data-role="packageList" href="javascript:;">查看我的红包</a>',
                        '</div>',
                    '</div>',
                    '<a v-on:click="onClose()" href="javascript:;" class="C_f_cls"></a>',
                '</div>',
            '</div>'
        ].join(''),
        user:[
            '<div class="top clearfix">',
                '<div class="name">',
                    '<div class="C_thumb" v-bind:class="[hasFrame ? normalClass : frameClass]" ><img class="img" v-bind:src="userinfo.headicon_70"><img v-if="frame" class="img_cover" v-bind:src="frame"></div><span>{{userinfo.nickname}}</span>',
                '</div>',
            '</div>',
        ].join(''),
        task:[
            '<div class="M_task F_cnt">',
                '<div class="C_maintl"><span>今日任务</span>',
                    '<a class="toggle toggle_up" href="javascript:;"></a>',
                '</div>',
                '<div v-for="item in list" class="item C_item">',
                    '<div class="item_tl">{{item.title}}</div>',
                    '<div class="progress">',
                        '<div class="benefit">',
                            '<i class="icon_mi"></i><i>{{item.reward}}</i>',
                        '</div>',
                        '<div class="bar"><i v-bind:style="{width: item.percent}"></i></div>',
                        '<div class="step">{{item.stage}}/{{item.total}}</div>',
                    '</div>',
                    '<template v-if="item.receiveFlag">',
                        '<span class="op icon_sucess"></span>',
                    '</template>',
                    '<template v-else-if="item.achieveFlag">',
                        '<a v-bind:href="item.href" v-on:click="onReceive(item.id)" class="op btn_get btn_mi">{{item.btnContent}}</a>',
                    '</template>',
                    '<template v-else>',
                        '<a v-bind:href="item.href" class="op btn_get">{{item.btnContent}}</a>',
                    '</template>',
                '</div>',
            '</div>',
        ].join(''),
        advertisement: [
            '<div class="M_slide F_cnt">',
                '<div class="C_maintl">大家都在看</div>',
                '<div class="slide clearfix">',
                    '<ul class="clearfix" v-bind:style="{width:widthTotal}">',
                        '<li v-for="item in list"><a v-bind:href="item.url"><img v-bind:src="item.img" v-bind:title="item.title" /></a></li>',
                    '</ul>',
                '</div>',
            '</div>',
        ].join(''),
        hero:[
            '<div v-if="length" class="M_rank F_cnt">',
                '<div class="C_maintl">今日任务完成光荣榜</div>',
                '<div class="lst_wrap C_item">',
                    '<ol class="lst ">',
                        '<li v-for="item in list" class="clearfix">',
                            '<div class="C_thumb C_thumb_nobrd">',
                                '<img class="img" v-bind:src="item.picture">',
                                '<img class="img_cover" v-bind:src="item.picture">',
                            '</div>',
                            '<span class="name">{{item.username}}</span><span class="overed">完成{{item.count}}个任务</span>',
                        '</li>',
                    '</ol>',
                '</div>',
            '</div>',
        ].join('')
    };
    /* beautify ignore:end */
    /* eslint-disable */

    module.exports = tpl;
});
